name: Provision GCP Resources via Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Job
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # - name: Authenticate to GCP
    #   run: |
    #     echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | base64 --decode > $HOME/gcp-key.json
    #     gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
    #     export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-key.json

    - name: Initialize Terraform
      run: terraform init
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_GOOGLE_CREDENTIALS }}

    - name: Plan Terraform Deployment
      run: terraform plan
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_GOOGLE_CREDENTIALS }}

    # - name: Apply Terraform Deployment
    #   run: terraform apply -auto-approve