name: Provision GCP Resources via Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      run: |
        echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | base64 --decode > $HOME/gcp-key.json
        gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform Deployment
      run: terraform plan

    # - name: Apply Terraform Deployment
    #   run: terraform apply -auto-approve